version: '3'
services:
  Tomcat:
    image: nclcloudcomputing/javabenchmarkapp
    ports:
     - "8080:8080"
    deploy:
      replicas: 2
      resources:
       reservations:
        cpus: "0.5"
        memory: 100M
    networks:
      - webnet
  Mongo_DB:
    image: mongo
    ports:
      - "8081:27017"
    volumes:
      - "./mongoDB_vol:/var/lib/mongodb"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  Visualiser:
    image: dockersamples/visualizer:stable
    ports:
      - "8082:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
